imageRowIncrease: 1
imageColIncrease: 1
cameraRealiableDis: 8 
pointCloudLeafSize: 0.2
start_frame: 2000
end_frame: 2460

mapSave: true
data_folder: "/home/zjl/semantic_3d_avp_ws/src/semantic_3d_avp/data/zjg2_2023-2/"
scene: 3  #yt 1 zjg1 2 zjg2 3 yq 4
localization_folder: "/home/zjl/semantic_3d_avp_ws/src/semantic_3d_avp/data/longterm_04/"
odomKeyFramDisThresh: 0.1 #0.1
odomKeyFramAngThresh: 5
InvalidColorThresh: 60
#IcpMaximumIterations最大迭代次数 IcpMaxCorrespondenceDistance搜索对应点的最大距离 IcpTransformationEpsilon收敛条件，当前位姿与上次位姿插值 IcpEuclideanFitnessEpsilon均方误差和
useICP: false
IcpMaxCorrespondenceDistance: 10 #10 1
IcpMaximumIterations: 100
IcpTransformationEpsilon: 1e-8 #1e-8
IcpEuclideanFitnessEpsilon: 1e-3 #0.01 #0.01
icpFitnessScoreThresh: 2000
useNDT: false
uselidar: false
myuseNDT_ICP: false
useplane: true
usemyICP: false
#ndtResolution网格大小 
ndtTransformationEpsilon: 0.01
ndtResolution: 1.0
ndtFitnessScoreThresh: 10
useNDT_ICP: true
useNDT_GICP: false
useNDT_PICP: false
use_sac_ndt: false
useglobalfilter: true
cube_localization: true
cube_ass: false
imagecutrow: 200 
imagecutrow1: 200 
imagecutcol: 100 
refacity: false
usewhite: false
transfer_surround: true
dynacut: false
thre_low: -4
thre_high: 4
tx: 0
ty: -0.4 
tz: 0
troll: 0
tpitch: 0
tyaw: 0.05 
#-45.43584397020063 87.47325584310548 0 0.040808826241787444 0.012388966649970017 0.7013680838961137 0.7115222864380338
init_x: -45.43584397020063
init_y: 87.47325584310548
init_z: 0
init_rx: 0.040808826241787444
init_ry: 0.012388966649970017
init_rz: 0.7013680838961137
init_rw: 0.7115222864380338