imageRowIncrease: 1
imageColIncrease: 1
cameraRealiableDis: 8 
pointCloudLeafSize: 0.2

start_frame: 4105 
end_frame: 5287 
run_mode: 0
mapSave: true
data_folder: "/home/zjl/semantic_3d_avp_ws/src/semantic_3d_avp/data/map_zjg2/"
scene: 3  #yt 1 zjg1 2 zjg2 3 yq 4
save_directory: "/home/zjl/semantic_3d_avp_ws/src/semantic_3d_avp/data/slam_03/"
mapSaveLocation: "/home/zjl/semantic_3d_avp_ws/src/semantic_3d_avp/data/slam_03/slam_03.pcd" #-aligen-trans0.4

odomKeyFramDisThresh: 0.1
odomKeyFramAngThresh: 5
InvalidColorThresh: 60
#IcpMaximumIterations最大迭代次数 IcpMaxCorrespondenceDistance搜索对应点的最大距离 IcpTransformationEpsilon收敛条件，当前位姿与上次位姿插值 IcpEuclideanFitnessEpsilon均方误差和
useICP: false
IcpMaxCorrespondenceDistance: 10 #10 1
IcpMaximumIterations: 100
IcpTransformationEpsilon: 1e-8 #1e-8
IcpEuclideanFitnessEpsilon: 1e-3 #0.01 #0.01
icpFitnessScoreThresh: 2000
useNDT: true
usevins: true
uselidar: false
myuseNDT_ICP: false
useplane: true
usemyICP: false
#ndtResolution网格大小 
ndtTransformationEpsilon: 0.01
ndtResolution: 1.0
ndtFitnessScoreThresh: 10
useNDT_ICP: true
useNDT_GICP: false
useNDT_PICP: false
use_sac_ndt: false
useglobalfilter: true
imagecutrow: 0
imagecutrow1: 0
imagecutcol: 0
refacity: false
usewhite: false
transfer_surround: true
dynacut: false
thre_low: -4
thre_high: 4
tx: 0
ty: -0.4 
tz: 0
troll: 0
tpitch: 0
tyaw: 0.05

#-241.93395535305453 75.9021748403008 0 0.030234685991686515 0.000893947294175801 0.7074628637863832 0.7061029393681838
init_x: -241.93395535305453
init_y: 75.9021748403008
init_z: 0
init_rx: 0.030234685991686515
init_ry: 0.000893947294175801
init_rz: 0.7074628637863832
init_rw: 0.7061029393681838